name: Lighthouse
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install Dependencies --legacy-peer-deps
        run: npm install
      - name: Run Lighthouse
        run: npm run lighthouse
